/**
 * usage-record.ts
 * ----------------
 * Domain entity representing a single agent execution.
 *
 * We keep "fresh" tokens separate from cache-served tokens, because they
 * have different rates and mixing them would distort both the real cost and
 * the future estimates.
 */

/** Immutable record of a single agent run. */
export interface UsageRecord {
  /** Grouping key: estimates are computed PER task type. */
  taskType: string;

  /** Input tokens sent to the model. */
  inputTokens: number;

  /** Output tokens generated by the model. */
  outputTokens: number;

  /** Input tokens written to cache (higher rate). */
  cacheCreationTokens: number;

  /** Input tokens read from cache (reduced rate). */
  cacheReadTokens: number;

  /** Real cost in USD reported by the SDK, if available. */
  costUsd: number;

  /** Total run duration in milliseconds. */
  durationMs: number;
}
