 import { Ssp } from './types';

/**
 * SSPs whose `sellers.json` files are ingested, sorted alphabetically by domain.
 * `numericSellerId` marks SSPs that publish integer seller ids.
 */
export const ssps: Ssp[] = [
  { domain: 'video.unrulymedia.com', numericSellerId: false },
  { domain: 'adagio.io', numericSellerId: true },
  { domain: 'pubmatic.com', numericSellerId: true },
  { domain: 'conversantmedia.com', numericSellerId: true },
  { domain: 'triplelift.com', numericSellerId: true },
  { domain: 'teads.tv', numericSellerId: true },
  { domain: 'gumgum.com', numericSellerId: true },
  { domain: 'sellers.teads.tv', numericSellerId: true },
  { domain: 'smartadserver.com', numericSellerId: true },
  { domain: 'improvedigital.com', numericSellerId: true },
  { domain: 'lijit.com', numericSellerId: true },
  { domain: 'loopme.com', numericSellerId: true },
  { domain: 'sharethrough.com', numericSellerId: true },
  { domain: 'consumable.com', numericSellerId: true },
  { domain: 'kargo.com', numericSellerId: true },
  { domain: 'stroeer.com', numericSellerId: true },
  { domain: 'themediagrid.com', numericSellerId: false },
  { domain: 'aps.amazon.com', numericSellerId: false },
  { domain: 'aralego.com', numericSellerId: false },
  { domain: 'media.net', numericSellerId: false },
  { domain: '33across.com', numericSellerId: false },
  { domain: 'seedtag.com', numericSellerId: false },
  { domain: 'nobid.io', numericSellerId: true },
  { domain: 'sonobi.com', numericSellerId: false },
  { domain: 'appnexus.com', numericSellerId: true },
  { domain: 'indexexchange.com', numericSellerId: true },
  { domain: 'undertone.com', numericSellerId: true },
  { domain: 'adyoulike.com', numericSellerId: false },
  { domain: 'adform.com', numericSellerId: true },
  { domain: 'nativo.com', numericSellerId: true },
  { domain: 'beachfront.com', numericSellerId: true },
  { domain: 'lkqd.com', numericSellerId: true },
  { domain: 'smaato.com', numericSellerId: true },
  { domain: 'fyber.com', numericSellerId: true },
  { domain: 'synacor.com', numericSellerId: true },
  { domain: 'infolinks.com', numericSellerId: true },
  { domain: 'chocolateplatform.com', numericSellerId: true },
  { domain: 'pulsepoint.com', numericSellerId: true },
  { domain: 'aol.com', numericSellerId: true },
  { domain: 'cpmstar.com', numericSellerId: true },
  { domain: 'yahoo.com', numericSellerId: true },
  { domain: 'rubiconproject.com', numericSellerId: true },
  { domain: 'taboola.com', numericSellerId: true },
  { domain: 'convergedigital.com', numericSellerId: true },
  { domain: 'emxdgt.com', numericSellerId: true },
  { domain: 'impact-ad.jp', numericSellerId: true },
  { domain: 'richaudience.com', numericSellerId: false },
  { domain: 'yieldmo.com', numericSellerId: true },
].sort((a, b) => a.domain.localeCompare(b.domain));
